tmp_dir = "tmp/air"

[build]
include_dir = ["api", "cmd", "internal", "pkg"]
pre_cmd = [
    "rm -f tmp/air/runtime-operator"
]
cmd = "go build -o tmp/air/runtime-operator ./cmd"
bin = "tmp/air/runtime-operator"
args_bin = ["-json-log"]
send_interrupt = true
rerun = true
stop_on_error = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true

[proxy]
enabled = false
