namespace: operator-dev

resources:
  - namespace.yaml
  - wasmcloud.yaml

images:
  - name: wasmcloud
    newName: ghcr.io/wasmcloud/wasmcloud
    newTag: canary
  - name: nats
    newName: nats
    newTag: 2.10.22-alpine
  - name: nats-config-reloader
    newName: natsio/nats-server-config-reloader
    newTag: 0.16.0
