apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wasmcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wasmcloud
    spec:
      containers:
        - name: nats
          image: nats
          imagePullPolicy: Always
          args:
            - -js
            - --addr
            - "0.0.0.0"
            - --port
            - "4222"
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - "-c"
                  - "while ! nc localhost 4222; do sleep 1; done"

        - name: wasmcloud
          image: wasmcloud
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: trace
            - name: WASMCLOUD_HEARTBEAT_INTERVAL
              value: "5"
            - name: WASMCLOUD_EXPERIMENTAL_FEATURES
              value: "builtin-messaging,builtin-http"
            - name: WASMCLOUD_STRUCTURED_LOGGING_ENABLED
              value: "true"
            - name: WASMCLOUD_LATTICE
              value: default
            - name: WASMCLOUD_LABEL_kubernetes
              value: "true"
            - name: WASMCLOUD_LABEL_hostgroup
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['wasmcloud-hostgroup']
            - name: WASMCLOUD_LABEL_kubernetes_pod_name
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: WASMCLOUD_LABEL_kubernetes_node_name
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          ports:
            - name: local
              containerPort: 8080
              protocol: TCP
            - name: remote
              containerPort: 8081
              protocol: TCP

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: wasmcloud
  name: nats
spec:
  selector:
    app.kubernetes.io/name: wasmcloud
  internalTrafficPolicy: Cluster
  ports:
    - appProtocol: tcp
      name: nats
      port: 4222
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: wasmcloud
  name: nats-headless
spec:
  selector:
    app.kubernetes.io/name: wasmcloud
  clusterIP: None
  internalTrafficPolicy: Cluster
  ports:
    - appProtocol: tcp
      name: nats
      port: 4222
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: wasmcloud
  name: wasmcloud-headless
spec:
  selector:
    app.kubernetes.io/name: wasmcloud
  clusterIP: None
  internalTrafficPolicy: Cluster
  ports:
    - appProtocol: tcp
      name: local
      port: 8080
      protocol: TCP
      targetPort: local
    - appProtocol: tcp
      name: remote
      port: 8081
      protocol: TCP
      targetPort: remote
