apiVersion: v1
kind: Secret
metadata:
  name: auth0-config
type: Opaque
stringData:
  issuer: "https://cosmonic-control-demo.us.auth0.com/"
  # dev auth0 client id/secret
  # locked down to google auth + auth0 dev google creds
  clientID: "xIJdvlsLzb7LTlUsfHv65e4lC218aPrm"
  clientSecret: "9Ep_KPXU5oE9dkZMnFx4B5EcSJEWL2MVOf4kD3fmqF5KYCie4Q9NxmUmtyWlU_F5"
  redirectURI: "http://localhost:8080/oidc/callback"
---
apiVersion: k8s.cosmonic.io/v1alpha1
kind: Cluster
metadata:
  name: example
spec:
  nexus:
    replicas: 3
    image: ghcr.io/cosmonic/nexus:canary
    imagePullSecrets:
      - name: ghcr
  console:
    image: ghcr.io/cosmonic/console:canary
    imagePullSecrets:
      - name: ghcr
    connectors:
      - id: "auth0"
        type: "oidc"
        name: "Login"
        configSecret:
          name: "auth0-config"
  operator:
    image: ghcr.io/cosmonic/runtime-operator:canary
    imagePullSecrets:
      - name: ghcr
---
apiVersion: k8s.cosmonic.io/v1alpha1
kind: HostGroup
metadata:
  name: default
spec:
  cluster:
    name: example
  replicas: 1
