---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - runtime.wasmcloud.dev
  resources:
  - artifacts
  - hosts
  - workloaddeployments
  - workloadreplicasets
  - workloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runtime.wasmcloud.dev
  resources:
  - artifacts/finalizers
  - hosts/finalizers
  - workloaddeployments/finalizers
  - workloadreplicasets/finalizers
  - workloads/finalizers
  verbs:
  - update
- apiGroups:
  - runtime.wasmcloud.dev
  resources:
  - artifacts/status
  - hosts/status
  - workloaddeployments/status
  - workloadreplicasets/status
  - workloads/status
  verbs:
  - get
  - patch
  - update
