# This rule is not used by the project operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over runtime.cosmonic.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: runtime-component-admin-role
rules:
- apiGroups:
  - runtime.cosmonic.io
  resources:
  - components
  verbs:
  - '*'
- apiGroups:
  - runtime.cosmonic.io
  resources:
  - components/status
  verbs:
  - get
