apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: Provider
metadata:
  name: http-server
spec:
  cluster:
    name: example
    namespace: default
  image: ghcr.io/wasmcloud/http-server:0.23.1
  replicas: 1
