apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: Link
metadata:
  name: example-to-http-server
spec:
  cluster:
    name: example
    namespace: default
  wit:
    namespace: wasi
    package: http
    interfaces:
      - incoming-handler
  source:
    provider:
      name: http-server
      namespace: default
    configFrom:
      - name: example
        namespace: default
  target:
    component:
      name: example
      namespace: default