extends: default
ignore:
  - "**/*"
  - "!.github/**/*.yaml"
  - "!.github/**/*.yml"
rules:
  document-start: disable 
  line-length:
    max: 120
  quoted-strings:
    quote-type: double
    required: false